// Nifty 50 stocks data
const nifty50Data = [
  { symbol: 'RELIANCE', name: 'Reliance Industries Ltd', sector: 'Energy', price: 2450.50 },
  { symbol: 'TCS', name: 'Tata Consultancy Services Ltd', sector: 'IT', price: 3650.75 },
  { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd', sector: 'Banking', price: 1620.30 },
  { symbol: 'INFY', name: 'Infosys Ltd', sector: 'IT', price: 1480.60 },
  { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd', sector: 'Banking', price: 980.40 },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever Ltd', sector: 'FMCG', price: 2380.90 },
  { symbol: 'ITC', name: 'ITC Ltd', sector: 'FMCG', price: 450.25 },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking', price: 620.80 },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel Ltd', sector: 'Telecom', price: 1250.45 },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd', sector: 'Banking', price: 1780.60 },
  { symbol: 'LT', name: 'Larsen & Toubro Ltd', sector: 'Infrastructure', price: 3420.30 },
  { symbol: 'AXISBANK', name: 'Axis Bank Ltd', sector: 'Banking', price: 1080.75 },
  { symbol: 'ASIANPAINT', name: 'Asian Paints Ltd', sector: 'Consumer Goods', price: 2980.50 },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India Ltd', sector: 'Automobile', price: 10250.80 },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd', sector: 'Pharma', price: 1180.40 },
  { symbol: 'TITAN', name: 'Titan Company Ltd', sector: 'Consumer Goods', price: 3250.60 },
  { symbol: 'WIPRO', name: 'Wipro Ltd', sector: 'IT', price: 480.30 },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement Ltd', sector: 'Cement', price: 9180.90 },
  { symbol: 'NESTLEIND', name: 'Nestle India Ltd', sector: 'FMCG', price: 2450.75 },
  { symbol: 'TATAMOTORS', name: 'Tata Motors Ltd', sector: 'Automobile', price: 780.50 },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance Ltd', sector: 'Financial Services', price: 7250.80 },
  { symbol: 'HCLTECH', name: 'HCL Technologies Ltd', sector: 'IT', price: 1380.40 },
  { symbol: 'POWERGRID', name: 'Power Grid Corporation of India Ltd', sector: 'Power', price: 245.60 },
  { symbol: 'NTPC', name: 'NTPC Ltd', sector: 'Power', price: 320.30 },
  { symbol: 'TECHM', name: 'Tech Mahindra Ltd', sector: 'IT', price: 1180.90 },
  { symbol: 'ONGC', name: 'Oil and Natural Gas Corporation Ltd', sector: 'Energy', price: 250.75 },
  { symbol: 'TATASTEEL', name: 'Tata Steel Ltd', sector: 'Steel', price: 135.50 },
  { symbol: 'ADANIPORTS', name: 'Adani Ports and Special Economic Zone Ltd', sector: 'Infrastructure', price: 1280.80 },
  { symbol: 'COALINDIA', name: 'Coal India Ltd', sector: 'Mining', price: 420.40 },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd', sector: 'Financial Services', price: 1650.60 },
  { symbol: 'DIVISLAB', name: 'Divi\'s Laboratories Ltd', sector: 'Pharma', price: 3580.30 },
  { symbol: 'DRREDDY', name: 'Dr. Reddy\'s Laboratories Ltd', sector: 'Pharma', price: 6250.90 },
  { symbol: 'EICHERMOT', name: 'Eicher Motors Ltd', sector: 'Automobile', price: 4680.75 },
  { symbol: 'GRASIM', name: 'Grasim Industries Ltd', sector: 'Cement', price: 2180.50 },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd', sector: 'Automobile', price: 4250.80 },
  { symbol: 'HINDALCO', name: 'Hindalco Industries Ltd', sector: 'Metals', price: 620.40 },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank Ltd', sector: 'Banking', price: 1380.60 },
  { symbol: 'JSWSTEEL', name: 'JSW Steel Ltd', sector: 'Steel', price: 880.30 },
  { symbol: 'MANDO', name: 'Mahindra & Mahindra Ltd', sector: 'Automobile', price: 1950.90 },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance Company Ltd', sector: 'Insurance', price: 1480.50 },
  { symbol: 'SHREECEM', name: 'Shree Cement Ltd', sector: 'Cement', price: 26500.80 },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products Ltd', sector: 'FMCG', price: 980.40 },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise Ltd', sector: 'Healthcare', price: 5680.30 },
  { symbol: 'BRITANNIA', name: 'Britannia Industries Ltd', sector: 'FMCG', price: 4850.75 },
  { symbol: 'CIPLA', name: 'Cipla Ltd', sector: 'Pharma', price: 1380.50 },
  { symbol: 'UPL', name: 'UPL Ltd', sector: 'Chemicals', price: 780.80 },
  { symbol: 'ADANIENT', name: 'Adani Enterprises Ltd', sector: 'Infrastructure', price: 2680.40 },
  { symbol: 'BPCL', name: 'Bharat Petroleum Corporation Ltd', sector: 'Energy', price: 580.60 },
  { symbol: 'VEDL', name: 'Vedanta Ltd', sector: 'Metals', price: 420.30 },
  { symbol: 'TATAPOWER', name: 'Tata Power Company Ltd', sector: 'Power', price: 380.90 },
];

export default nifty50Data;