// Nifty 50 stocks data - Updated November 2025
const nifty50Data = [
  { symbol: 'RELIANCE', name: 'Reliance Industries Ltd', sector: 'Energy', price: 1285.50 },
  { symbol: 'TCS', name: 'Tata Consultancy Services Ltd', sector: 'IT', price: 3950.75 },
  { symbol: 'HDFCBANK', name: 'HDFC Bank Ltd', sector: 'Banking', price: 1750.30 },
  { symbol: 'INFY', name: 'Infosys Ltd', sector: 'IT', price: 1820.60 },
  { symbol: 'ICICIBANK', name: 'ICICI Bank Ltd', sector: 'Banking', price: 1260.40 },
  { symbol: 'HINDUNILVR', name: 'Hindustan Unilever Ltd', sector: 'FMCG', price: 2385.90 },
  { symbol: 'ITC', name: 'ITC Ltd', sector: 'FMCG', price: 465.25 },
  { symbol: 'SBIN', name: 'State Bank of India', sector: 'Banking', price: 820.80 },
  { symbol: 'BHARTIARTL', name: 'Bharti Airtel Ltd', sector: 'Telecom', price: 1650.45 },
  { symbol: 'KOTAKBANK', name: 'Kotak Mahindra Bank Ltd', sector: 'Banking', price: 1895.60 },
  { symbol: 'LT', name: 'Larsen & Toubro Ltd', sector: 'Infrastructure', price: 3685.30 },
  { symbol: 'AXISBANK', name: 'Axis Bank Ltd', sector: 'Banking', price: 1145.75 },
  { symbol: 'ASIANPAINT', name: 'Asian Paints Ltd', sector: 'Consumer Goods', price: 2450.50 },
  { symbol: 'MARUTI', name: 'Maruti Suzuki India Ltd', sector: 'Automobile', price: 12850.80 },
  { symbol: 'SUNPHARMA', name: 'Sun Pharmaceutical Industries Ltd', sector: 'Pharma', price: 1780.40 },
  { symbol: 'TITAN', name: 'Titan Company Ltd', sector: 'Consumer Goods', price: 3540.60 },
  { symbol: 'WIPRO', name: 'Wipro Ltd', sector: 'IT', price: 565.30 },
  { symbol: 'ULTRACEMCO', name: 'UltraTech Cement Ltd', sector: 'Cement', price: 11280.90 },
  { symbol: 'NESTLEIND', name: 'Nestle India Ltd', sector: 'FMCG', price: 2285.75 },
  { symbol: 'TATAMOTORS', name: 'Tata Motors Ltd', sector: 'Automobile', price: 985.50 },
  { symbol: 'BAJFINANCE', name: 'Bajaj Finance Ltd', sector: 'Financial Services', price: 6850.80 },
  { symbol: 'HCLTECH', name: 'HCL Technologies Ltd', sector: 'IT', price: 1850.40 },
  { symbol: 'POWERGRID', name: 'Power Grid Corporation of India Ltd', sector: 'Power', price: 325.60 },
  { symbol: 'NTPC', name: 'NTPC Ltd', sector: 'Power', price: 385.30 },
  { symbol: 'TECHM', name: 'Tech Mahindra Ltd', sector: 'IT', price: 1685.90 },
  { symbol: 'ONGC', name: 'Oil and Natural Gas Corporation Ltd', sector: 'Energy', price: 285.75 },
  { symbol: 'TATASTEEL', name: 'Tata Steel Ltd', sector: 'Steel', price: 165.50 },
  { symbol: 'ADANIPORTS', name: 'Adani Ports and Special Economic Zone Ltd', sector: 'Infrastructure', price: 1485.80 },
  { symbol: 'COALINDIA', name: 'Coal India Ltd', sector: 'Mining', price: 485.40 },
  { symbol: 'BAJAJFINSV', name: 'Bajaj Finserv Ltd', sector: 'Financial Services', price: 1785.60 },
  { symbol: 'DIVISLAB', name: 'Divi\'s Laboratories Ltd', sector: 'Pharma', price: 5980.30 },
  { symbol: 'DRREDDY', name: 'Dr. Reddy\'s Laboratories Ltd', sector: 'Pharma', price: 1285.90 },
  { symbol: 'EICHERMOT', name: 'Eicher Motors Ltd', sector: 'Automobile', price: 4985.75 },
  { symbol: 'GRASIM', name: 'Grasim Industries Ltd', sector: 'Cement', price: 2685.50 },
  { symbol: 'HEROMOTOCO', name: 'Hero MotoCorp Ltd', sector: 'Automobile', price: 4850.80 },
  { symbol: 'HINDALCO', name: 'Hindalco Industries Ltd', sector: 'Metals', price: 685.40 },
  { symbol: 'INDUSINDBK', name: 'IndusInd Bank Ltd', sector: 'Banking', price: 1485.60 },
  { symbol: 'JSWSTEEL', name: 'JSW Steel Ltd', sector: 'Steel', price: 985.30 },
  { symbol: 'MANDO', name: 'Mahindra & Mahindra Ltd', sector: 'Automobile', price: 2950.90 },
  { symbol: 'SBILIFE', name: 'SBI Life Insurance Company Ltd', sector: 'Insurance', price: 1685.50 },
  { symbol: 'SHREECEM', name: 'Shree Cement Ltd', sector: 'Cement', price: 27850.80 },
  { symbol: 'TATACONSUM', name: 'Tata Consumer Products Ltd', sector: 'FMCG', price: 1185.40 },
  { symbol: 'APOLLOHOSP', name: 'Apollo Hospitals Enterprise Ltd', sector: 'Healthcare', price: 6985.30 },
  { symbol: 'BRITANNIA', name: 'Britannia Industries Ltd', sector: 'FMCG', price: 4985.75 },
  { symbol: 'CIPLA', name: 'Cipla Ltd', sector: 'Pharma', price: 1485.50 },
  { symbol: 'UPL', name: 'UPL Ltd', sector: 'Chemicals', price: 585.80 },
  { symbol: 'ADANIENT', name: 'Adani Enterprises Ltd', sector: 'Infrastructure', price: 2985.40 },
  { symbol: 'BPCL', name: 'Bharat Petroleum Corporation Ltd', sector: 'Energy', price: 615.60 },
  { symbol: 'VEDL', name: 'Vedanta Ltd', sector: 'Metals', price: 485.30 },
  { symbol: 'TATAPOWER', name: 'Tata Power Company Ltd', sector: 'Power', price: 485.90 },
];

export default nifty50Data;